{
  "jobs": {
    "action": {
      "runs-on": "ubuntu-22.04",
      "steps": [
        {
          "uses": "actions/checkout@v4.1.2"
        },
        {
          "uses": "./"
        },
        {
          "run": "cabal-gild --version"
        }
      ]
    }
  },
  "name": "Workflow",
  "on": {
    "push": null
  }
}
